services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 10s
      retries: 5

  fastapi:
    build: .
    container_name: fastapi
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app 
    env_file:
      - .env
    environment:
      - RUNNING_IN_DOCKER=true 
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"